#!/bin/zsh
# Quick automation management commands for Hot Durham project

echo "🤖 Hot Durham Automation Quick Commands"
echo "======================================"
echo ""
echo "📊 CHECK STATUS:"
echo "   scripts/automation/setup_maintenance_automation.sh status"
echo ""
echo "🧪 TEST AUTOMATION:"
echo "   scripts/automation/setup_maintenance_automation.sh test"
echo ""
echo "🔧 MANUAL RUNS:"
echo "   scripts/maintenance/cleanup_project.sh          # Clean up files now"
echo "   scripts/maintenance/security_check.sh           # Security scan now"
echo "   scripts/automation/maintenance.sh              # Full maintenance now"
echo "   scripts/automation/automated_maintenance.sh    # Run automation now"
echo ""
echo "📋 VIEW LOGS:"
echo "   ls -la logs/automated_maintenance_*.log | tail -5"
echo "   tail -20 logs/automated_maintenance_*.log"
echo ""
echo "⚙️ MANAGE AUTOMATION:"
echo "   scripts/automation/setup_maintenance_automation.sh install-cron     # Install"
echo "   scripts/automation/setup_maintenance_automation.sh uninstall-cron   # Remove"
echo "   crontab -l                                          # View all cron jobs"
echo ""
echo "🔔 FORCE RUN WITH NOTIFICATIONS:"
echo "   scripts/automation/automated_maintenance.sh --force-weekly"
echo ""
echo "📖 FULL GUIDE:"
echo "   cat AUTOMATION_SETUP_GUIDE.md"
