version: 2
sources:
  - name: raw_sources
    description: Raw ingestion tables from sensor pipelines
    freshness:
      warn_after: {count: 26, period: hour}
      error_after: {count: 36, period: hour}
    loaded_at_field: timestamp
    tables:
      - name: sensor_readings_wu_raw
        description: Weather Underground raw observations
        loaded_at_field: obsTimeUtc
      - name: sensor_readings_tsi_raw
        description: TSI device raw observations
        loaded_at_field: cloud_timestamp
