name: Daily Sensor Readings Merge

on:
  schedule:
    - cron: '10 7 * * *' # 07:10 UTC daily, after verification (adjust as needed)
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  BQ_PROJECT: durham-weather-466502
  BQ_DATASET: sensors

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token

      - name: Merge yesterday partitions (auto-detect staging)
        run: |
          YESTERDAY=$(date -u -d 'yesterday' +%F)
          echo "Merging date $YESTERDAY"
          python scripts/merge_sensor_readings.py \
            --project "$BQ_PROJECT" \
            --dataset "$BQ_DATASET" \
            --date "$YESTERDAY" \
            --auto-detect-staging \
            --update-only-if-changed

      - name: Upload merge logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merge-logs
          path: ./*.log