name: dbt-compile
on:
  pull_request:
    paths:
      - 'transformations/dbt/**'
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch: {}

env:
  GCP_PROJECT_ID: durham-weather-466502
  BQ_DATASET: sensors

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install base deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dbt.txt
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token
      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'EOF'
          sensor_transforms:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: oauth
                project: ${{ env.GCP_PROJECT_ID }}
                dataset: ${{ env.BQ_DATASET }}
                threads: 4
                timeout_seconds: 300
                priority: interactive
                location: US
          EOF
      - name: dbt deps
        run: dbt deps --project-dir transformations/dbt
      - name: dbt compile
        run: |
          PROC_DATE=$(date -u +%Y-%m-%d)
          dbt compile --project-dir transformations/dbt --profiles-dir ~/.dbt \
            --vars "proc_date:$PROC_DATE,project:${{ env.GCP_PROJECT_ID }}"
