name: Execute Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: "Cloud Run Job name"
        required: false
        default: weather-data-uploader
      region:
        description: "Region"
        required: false
        default: us-east1
      date:
        description: "Single date to run (YYYY-MM-DD). Cannot be used with start_date/end_date"
        required: false
      start_date:
        description: "Start date for range (YYYY-MM-DD). Must be used with end_date"
        required: false
      end_date:
        description: "End date for range (YYYY-MM-DD). Must be used with start_date"
        required: false

env:
  PROJECT_ID: durham-weather-466502

jobs:
  run-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: 'projects/441117079833/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Execute Job
        env:
          JOB_NAME: ${{ github.event.inputs.job_name }}
          REGION: ${{ github.event.inputs.region }}
          DATE: ${{ github.event.inputs.date }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
        run: |
          bash scripts/run_cr_job.sh
