name: Row Count Threshold Check

on:
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch:

env:
  BQ_PROJECT: durham-weather-466502
  BQ_DATASET: sensors

jobs:
  thresholds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token
      - name: Run threshold check (yesterday)
        run: |
          YESTERDAY=$(date -u -d 'yesterday' +%F)
          python scripts/check_row_thresholds.py --project ${{ env.BQ_PROJECT }} --dataset ${{ env.BQ_DATASET }} --date $YESTERDAY
