name: Seed sensor_id_map (identity)

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'GCP Project ID'
        required: false
        default: 'durham-weather-466502'
      dataset_id:
        description: 'BigQuery Dataset ID'
        required: false
        default: 'sensors'

permissions:
  contents: read
  id-token: write # for Workload Identity Federation (OIDC) to GCP

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token

      - name: Seed identity rows
        run: |
          PROJECT_ID="${{ github.event.inputs.project_id }}"
          DATASET_ID="${{ github.event.inputs.dataset_id }}"
          echo "Seeding identity mapping into ${PROJECT_ID}.${DATASET_ID}.sensor_id_map"
          python scripts/seed_sensor_id_map.py --project "$PROJECT_ID" --dataset "$DATASET_ID" --execute
