name: Execute Transformations

on:
  schedule:
    - cron: '25 07 * * *' # 07:25 UTC daily after ingestion & loads
  workflow_dispatch: {}

env:
  PROJECT_ID: durham-weather-466502
  DATASET_ID: sensors

jobs:
  run-transformations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Gate on successful Nightly E2E (scheduled runs only)
        if: github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow_id = 'e2e-nightly.yml';
            const resp = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id,
              branch: 'main',
              status: 'completed',
              per_page: 5,
            });
            const runs = resp.data.workflow_runs.filter(r => r.conclusion === 'success');
            if (!runs.length) {
              core.setFailed('No successful e2e-nightly runs found');
              return;
            }
            const latest = new Date(runs[0].updated_at);
            const now = new Date();
            const ageHours = (now - latest) / (1000*60*60);
            if (ageHours > 8) {
              core.setFailed(`Latest e2e-nightly run too old: ${latest.toISOString()} (${ageHours.toFixed(1)}h)`);
            } else {
              core.info(`Found recent successful e2e-nightly at ${latest.toISOString()} (${ageHours.toFixed(1)}h old)`);
            }
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install deps
        run: |
          uv venv
          uv pip sync requirements.txt
          uv pip sync requirements-dev.txt || true

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Run transformations
        env:
          BQ_PROJECT: ${{ env.PROJECT_ID }}
        run: |
          PROC_DATE=$(date -u -d 'yesterday' +%Y-%m-%d)
          echo "Processing date: $PROC_DATE"
          uv run python scripts/run_transformations.py --project $BQ_PROJECT --dataset ${{ env.DATASET_ID }} --date $PROC_DATE --execute
      - name: Teams notify failure
        if: failure() && env.TEAMS_WEBHOOK_URL != ''
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          python scripts/notify_teams.py \
            --webhook "$TEAMS_WEBHOOK_URL" \
            --title "Transformations FAILED" \
            --text "Date: $(date -u +%Y-%m-%d)\nRepo: $GITHUB_REPOSITORY\nSHA: $GITHUB_SHA\nRun: $GITHUB_RUN_ID"
